[RTF-761] Separate FillRequiredProperties from workspace create; fill…
relativitydev/relativity.testing.framework.api pull request #171
Opened 2021-09-17 15:56 UTC by briantoms

… blank properties from resource pool where applicable

Complete the following tasks before merging in your PR:
- [x] If this is a user facing change, update [version.txt](https://github.com/relativitydev/relativity.testing.framework.api/blob/master/version.txt) and [CHANGELOG.md](https://github.com/relativitydev/relativity.testing.framework.api/blob/master/CHANGELOG.md)

2021-09-17 15:57 UTC, briantoms commented
I wanted to divide the fixture for the new strategy into regions, but [StyleCop does not approve of regions](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1124.md).

2021-09-17 15:59 UTC, briantoms commented on source/Relativity.Testing.Framework.Api.Tests/Strategies/Workspace/WorkspaceFillRequiredPropertiesStrategyFixture.cs
> +		}
I wanted to add tests here around selecting matters from the appropriate client, when a client is provided but a matter is not, but unfortunately `ObjectQuery` is almost impossible to mock due to the lack of an interface (and that refactoring would have been _way_ out of scope). We'll have to rely on the L3 test for this for now.

2021-09-17 16:57 UTC, briantoms commented on source/Relativity.Testing.Framework.Api/Strategies/Workspaces/WorkspaceFillRequiredPropertiesStrategy.cs
> +			}
These three could probably be moved to the RTF repo, because the defaults are either random or constant.

2021-09-20 08:21 UTC, klaudiaknafel commented on source/Relativity.Testing.Framework.Api/Strategies/Workspaces/WorkspaceFillRequiredPropertiesStrategy.cs
> +			if (entity.Name == null)
what about when the name is empty or whitespace?

2021-09-20 08:27 UTC, klaudiaknafel commented on source/Relativity.Testing.Framework.Api/Strategies/Workspaces/WorkspaceFillRequiredPropertiesStrategy.cs
> +			if (entity.Name == null)
same for the next ones

2021-09-20 08:27 UTC, klaudiaknafel commented on source/Relativity.Testing.Framework.Api/Strategies/Workspaces/WorkspaceFillRequiredPropertiesStrategy.cs
> +					throw ObjectNotFoundException.CreateForNotFoundByName<Workspace>(templateWorkspace.Name);
can we have extracted methods (e.g. here something like  GetTemplateByName) for this else and for the first if? this will be easier and faster to read then

2021-09-20 14:42 UTC, matthew-wiemer requested changes
Tests or explain why no new tests, please.

2021-09-20 15:31 UTC, paulletang approved these changes

2021-09-20 15:31 UTC, paulletang commented on source/Relativity.Testing.Framework.Api/Strategies/Workspaces/WorkspaceFillRequiredPropertiesStrategy.cs
> +					throw ObjectNotFoundException.CreateForNotFoundByName<Workspace>(templateWorkspace.Name);
I think this would be helpful, yeah.

- [ ] Make functions more granular

2021-09-20 15:31 UTC, paulletang commented on source/Relativity.Testing.Framework.Api/Strategies/Workspaces/WorkspaceFillRequiredPropertiesStrategy.cs
> +			if (entity.Name == null)
I think this would make the function more user friendly for this edge case, but it might be make our function overly opinionated.
This might prevent users from testing out some error scenarios if we go this route.

2021-09-20 16:04 UTC, briantoms commented on source/Relativity.Testing.Framework.Api/Strategies/Workspaces/WorkspaceFillRequiredPropertiesStrategy.cs
> +			if (entity.Name == null)
This was the existing behavior and I decided not to change it, since I didn't have a good reason to.

2021-09-20 18:21 UTC, matthew-wiemer reviewed
I wouldn't block a merge, but getting some tests in that cover when nothing comes back from Relativity could be a value-add in this change.

2021-09-20 18:21 UTC, matthew-wiemer commented on source/Relativity.Testing.Framework.Api.Tests/Strategies/Workspace/WorkspaceFillRequiredPropertiesStrategyFixture.cs
> +		public void SetDefaultMocks()
I might have missed it, but are there tests that cover when there aren't any mocked results? Or when there are mocked results, but they don't match what you are selecting on in the strategy?

I think that's one code path that might not be covered yet.

2021-09-20 18:21 UTC, matthew-wiemer commented on source/Relativity.Testing.Framework.Api.Tests/Strategies/Workspace/WorkspaceFillRequiredPropertiesStrategyFixture.cs
> +}
This is getting long enough that it seems like there are some distinct groupings of tests that all happen to share a setup. 

Is there a way this could be delineated with more specific fixtures?

2021-09-20 18:26 UTC, briantoms commented on source/Relativity.Testing.Framework.Api/Strategies/Workspaces/WorkspaceFillRequiredPropertiesStrategy.cs
> +				matter = _objectService.Query<Matter>().Where(x => x.Name, "Relativity Template").FirstOrDefault();
It's not LINQ, even though it looks like it. The `Where` clause actually gets used to build the query conditions.

ResourcePool, on the other hand, actually _is_ LINQ, but we only query once there because of the way the `if`/`else if`/`else` is structured.

2021-09-20 18:26 UTC, briantoms commented on source/Relativity.Testing.Framework.Api.Tests/Strategies/Workspace/WorkspaceFillRequiredPropertiesStrategyFixture.cs
> +}
I could split it into multiple fixtures, but I thought we only wanted one fixture per strategy. I agree it's very long.

2021-09-20 18:30 UTC, briantoms commented on source/Relativity.Testing.Framework.Api.Tests/Strategies/Workspace/WorkspaceFillRequiredPropertiesStrategyFixture.cs
> +		public void SetDefaultMocks()
The behavior when there aren't any results is all over the place. Some of them would just leave a `null` and presumably fail the create operation later; others throw various types of exceptions.

I wouldn't have a problem with adding tests to pin this behavior, but first we should make a conscious decision on what we want that behavior to be.

2021-09-20 19:38 UTC, paulletang commented on source/Relativity.Testing.Framework.Api.Tests/Strategies/Workspace/WorkspaceFillRequiredPropertiesStrategyFixture.cs
> +}
Our naming conventions dictate that the fixture is named after the class/file that is being tested.
If the file is too big, that might be an indicator that the class is trying to do too much.

2021-09-30 19:46 UTC, paulletang approved these changes

2021-09-30 20:00 UTC, paulletang approved these changes

2021-09-30 20:35 UTC, merged