Testeng 1865 add tiger lily tests and update sundrop
relativitydev/relativity.testing.framework.api pull request #254
Opened 2021-11-22 22:16 UTC by Sai-Nissankula

Complete the following tasks before merging in your PR:
- [ ] If this is a user facing change, update [version.txt](https://github.com/relativitydev/relativity.testing.framework.api/blob/master/version.txt) and [CHANGELOG.md](https://github.com/relativitydev/relativity.testing.framework.api/blob/master/CHANGELOG.md)

2021-11-22 22:18 UTC, briantoms requested changes

2021-11-22 22:18 UTC, briantoms commented on .github/workflows/ReleaseBranch.yaml
>    Publish:
You need to update what `Publish` depends on or it will never run

2021-11-22 22:19 UTC, briantoms commented
The PublishTestResults workflow (https://github.com/relativitydev/relativity.testing.framework.api/blob/master/.github/workflows/PublishTestResults.yaml) must also be updated.

2021-11-22 22:22 UTC, briantoms approved these changes

2021-11-22 22:47 UTC, paulletang commented
Lots of test failures in the new release.
Looks like something bombed out in setup.

2021-11-23 19:58 UTC, paulletang commented on source/Relativity.Testing.Framework.Api/ApiComponent.cs
> +		public const string SupportedRelativityVersionRange = "11.3 - 13.0";
How can we fix the tests so that this isn't an issue going forward?

2021-11-23 20:05 UTC, Sai-Nissankula commented on source/Relativity.Testing.Framework.Api/ApiComponent.cs
> +		public const string SupportedRelativityVersionRange = "11.3 - 13.0";
I made the flag default to false instead of true in the api component.

2021-11-23 20:07 UTC, paulletang commented on source/Relativity.Testing.Framework.Api/ApiComponent.cs
> +				GetValueOrDefault(PerformRelativityVersionCheckConfigurationKey, false);
Will this have any implications to the RTF code for our consumers?

Isn't there something in our test setup that is causing this that we can fix?

2021-11-23 20:15 UTC, Sai-Nissankula commented on source/Relativity.Testing.Framework.Api/ApiComponent.cs
> +				GetValueOrDefault(PerformRelativityVersionCheckConfigurationKey, false);
I am not sure which setup you are referring to here.

2021-11-23 20:16 UTC, Sai-Nissankula commented on source/Relativity.Testing.Framework.Api/ApiComponent.cs
> +				GetValueOrDefault(PerformRelativityVersionCheckConfigurationKey, false);
Can you please clarify?

2021-11-23 20:19 UTC, briantoms commented on source/Relativity.Testing.Framework.Api/ApiComponent.cs
> +		public const string SupportedRelativityVersionRange = "11.3 - 13.0";
I think we should either continue to manually update this with every new quarterly release, or just remove the upper bound of the version check completely. Feels weird to have a version check if we're not going to use it, and we still want to check the _lower_ bound so we don't have customers trying to use RTF against unsupported Server versions.

2021-11-23 20:34 UTC, briantoms approved these changes

2021-11-23 21:05 UTC, paulletang commented on source/Relativity.Testing.Framework.Api/ApiComponent.cs
> +				GetValueOrDefault(PerformRelativityVersionCheckConfigurationKey, false);
If you step through the code, I bet you will find where this is failing out.
I don't have a mental map of where it is right now.

2021-11-24 16:40 UTC, merged